# Generated by Django 3.2 on 2021-04-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInventaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currentQty',
            new_name='current_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stockQty',
            new_name='stock_quantity',
        ),
    ]
